services:
 app:
  container_name: app
  build: .
  ports:
   - "${SERVER_PORT}:${SERVER_PORT}"
  volumes:
   - .:/app
  environment:
   - DATABASE_HOST=database
   - DATABASE_DIALECT=postgres
   - TERM=xterm
  command: npm run dev

 database:
  container_name: database
  image: postgres:14
  ports:
   - ${DATABASE_PORT}:${DATABASE_PORT}
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=${DATABASE_USER}
   - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
   - POSTGRES_DB=${DATABASE_NAME}

volumes:
 postgres-data:
