services:
 app:
  container_name: app
  build: .
  environment:
   - DATABASE_HOST=database
   - STEAM_API_KEY=${STEAM_API_KEY?:err}
   - TERM=xterm
  depends_on:
   - database

 database:
  container_name: database
  image: postgres:14
